# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0002_auto_20170214_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='is_blind',
            field=models.BooleanField(default=False),
        ),
    ]
